# Mouse support
set -g mouse on

# History limit
set -g history-limit 10000

# Terminal title
set -g set-titles on

# Focus events
set -s focus-events on

# Clipboard integration
set -s set-clipboard on

# Split bindings
bind | split-window -h
bind - split-window -v

# Status bar
set -g @tmux_status_pane_title '#{=164:pane_title}'
set -g @tmux_status_path ' │ #[bg=#A79787] #{pane_current_path} #[default]'
set -g @tmux_status_prefix '#{?client_prefix, │ #[bg=#858DD8] PREFIX #[default],}'
set -g @tmux_status_clock_separator ' │ '
set -g status-right '#{E:@tmux_status_pane_title}#{E:@tmux_status_path}#{E:@tmux_status_prefix}#{E:@tmux_status_clock_separator}%H:%M %d-%b-%y'
set -g status-right-length 256

# RGB color support
set -as terminal-overrides ',xterm-256color:Tc'
