name: Edge base images

on:
  push:
    branches:
      - dev
    paths:
      - images/base/**

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/_images.yaml
    with:
      lane: edge
      images: all
