name: Edge Ansible image

on:
  push:
    branches:
      - dev
    paths:
      - images/ansible/**

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/_images.yaml
    with:
      lane: edge
      images: ansible
